### ISSUE TITLE
The software needs the MKVtoolnix to be installed on C drive

### ISSUE THREAD

**Issue by hwyedba4** [H3X1C/MKVToolNixWrapper#1]
But I have installed it somewhere else. Please add an option to choose a different path for it

**Comment by H3X1C** [comment]
Sorry for the delay in the response I missed the notification.
Very true it's hardcoded, In the next version I will add support to prompt the user to select it's location if it cannot be found on the C drive. It will need a config file too so you aren't prompted every time you open the app. I will add it to my todo list.
Thanks for the feedback

**Comment by H3X1C** [comment]
A quick update on this I have just released v1.0.0.4 which adds support for selecting a custom MKVmerge location, please give it a try and let me know if this resolves your issue :)
